blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug Report
    url: .github/ISSUE_TEMPLATE/bug_report.yml
    about: Laporkan bug atau error di Termux App Store dengan lengkap

  - name: âœ¨ Feature Request
    url: .github/ISSUE_TEMPLATE/feature_request.yml
    about: Ajukan ide atau fitur baru untuk Termux App Store

  - name: ğŸ†˜ Support / Help Request
    url: .github/ISSUE_TEMPLATE/support_request.yml
    about: Ajukan pertanyaan atau minta bantuan terkait Termux App Store
